USE ecommerce_shop;

SET FOREIGN_KEY_CHECKS=0;

-- Clear existing recipe data
TRUNCATE TABLE recipes;
TRUNCATE TABLE product_ingredients;
TRUNCATE TABLE ingredients;

-- Ensure Category 'Bia & Nước ngọt' exists
INSERT IGNORE INTO categories (name, slug, description, created_at) VALUES ('Bia & Nước ngọt', 'bia-nuoc-ngot', 'Các loại bia và nước giải khát', NOW());
SET @cat_id = (SELECT id FROM categories WHERE slug = 'bia-nuoc-ngot' LIMIT 1);

-- Insert Products from Images
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('6 chai tra xanh khong do vi chanh 455ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/6-chai-tra-xanh-khong-do-vi-chanh-455ml-202103290825331304.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('6 lon nuoc ngot co ga pepsi khong duong vi phuc bon tu 320ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/6-lon-nuoc-ngot-co-ga-pepsi-khong-duong-vi-phuc-bon-tu-320ml_202512251932405441.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('8 lon nuoc ngot coca cola 235ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/8-lon-nuoc-ngot-coca-cola-235ml_202601071618351835.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Bia sai gon lager lon 330ml thung 24 lon', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/bia-sai-gon-lager-lon-330ml-thung-24-lon_202601161315021080.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Loc 6 lon nuoc ngot 7 up 330ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/loc-6-lon-nuoc-ngot-7-up-330ml_202512231315411884.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Nuoc tang luc sting vi dau loc 6 lon cao 330ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/nuoc-tang-luc-sting-vi-dau-loc-6-lon-cao-330ml_202509291513317781.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Thung 24 chai lavie', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/thung-24-chai-lavie.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Thung 24 lon bia heineken silver 330ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/thung-24-lon-bia-heineken-silver-330ml_202512301355470171.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Thung 24 lon bia tiger lon cao 330ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/thung-24-lon-bia-tiger-lon-cao-330ml_202512301834559592.jpg', @cat_id, 1, NOW(), NOW());
INSERT INTO products (name, description, price, stock_quantity, image_url, category_id, is_active, created_at, updated_at) VALUES ('Thung 24 lon nuoc tang luc redbull thai kem va vitamin 250ml', 'Sản phẩm giải khát', 15000, 100, '/img/bia-nuoc-ngot/thung-24-lon-nuoc-tang-luc-redbull-thai-kem-va-vitamin-250ml_202505261544132034.jpg', @cat_id, 1, NOW(), NOW());

-- Insert Recipes
-- Insert Ingredients
INSERT INTO ingredients (name, created_at) VALUES ('Thịt ba chỉ', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Trứng gà', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Nước mắm', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Đường', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Hành tím', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Tiêu', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Cá', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Thịt gà', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Gừng', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Tỏi', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Sườn non', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Cà chua', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Giấm', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Thịt bò', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Hành tây', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Dầu hào', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Rau muống', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Muối', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Tôm', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Thịt băm', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Rau cải', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Đậu hũ', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Khổ qua', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Nấm mèo', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Cơm nguội', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Hành lá', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Gạo', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Ức gà', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Dầu olive', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Bông cải', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Cà rốt', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Đậu que', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Me', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Rau thơm', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Mì trứng', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Bún tươi', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Thịt heo', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Sả', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Mực', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Cần tây', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Bí đỏ', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Su su', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Ớt', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Mồng tơi', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Rong biển khô', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Dầu mè', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Bột chiên giòn', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Bơ', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Lạp xưởng', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Đậu Hà Lan', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Rau xà lách', NOW());
INSERT INTO ingredients (name, created_at) VALUES ('Nước', NOW());

-- Insert Recipes Data
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Thịt kho trứng', 'Thịt kho trứng ngon tuyệt', 40, 4, 'Easy', '[{"name":"Thịt ba chỉ","qty":"500g","note":"có mỡ nạc xen kẽ"},{"name":"Trứng gà","qty":"4 quả","note":"luộc chín, bóc vỏ"},{"name":"Nước mắm","qty":"3 muỗng canh","note":"nước mắm ngon"},{"name":"Đường","qty":"2 muỗng canh","note":"tạo màu và vị"},{"name":"Hành tím","qty":"2 củ","note":"băm nhỏ"},{"name":"Tiêu","qty":"1/2 muỗng cà phê","note":"rắc cuối"}]', '["Luộc trứng chín, bóc vỏ.","Thịt rửa sạch, cắt miếng vuông.","Ướp thịt với nước mắm, đường, tiêu 15 phút.","Phi hành tím cho thơm.","Cho thịt vào xào săn.","Thêm trứng và nước xâm xấp.","Kho nhỏ lửa đến khi nước sệt."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cá kho tộ', 'Cá kho tộ ngon tuyệt', 35, 4, 'Easy', '[{"name":"Cá","qty":"600g","note":"cá lóc hoặc basa"},{"name":"Nước mắm","qty":"3 muỗng canh","note":"ướp và kho"},{"name":"Đường","qty":"1.5 muỗng canh","note":"thắng màu"},{"name":"Hành tím","qty":"2 củ","note":"băm"},{"name":"Tiêu","qty":"1/2 muỗng cà phê","note":"tạo mùi"}]', '["Cá làm sạch, cắt khúc.","Ướp cá với gia vị 15 phút.","Thắng đường đến màu cánh gián.","Xếp cá vào nồi, cho nước màu.","Thêm nước xâm xấp.","Kho lửa nhỏ 25 phút.","Rắc tiêu trước khi tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Gà kho gừng', 'Gà kho gừng ngon tuyệt', 30, 4, 'Easy', '[{"name":"Thịt gà","qty":"700g","note":"chặt miếng vừa ăn"},{"name":"Gừng","qty":"30g","note":"thái sợi"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"ướp"},{"name":"Đường","qty":"1 muỗng canh","note":"cân vị"},{"name":"Tỏi","qty":"3 tép","note":"băm"}]', '["Ướp gà với gia vị 15 phút.","Phi tỏi cho thơm.","Cho gà vào xào săn.","Thêm gừng đảo đều.","Cho nước xâm xấp.","Kho nhỏ lửa 20 phút.","Nêm lại cho vừa."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Sườn xào chua ngọt', 'Sườn xào chua ngọt ngon tuyệt', 35, 4, 'Easy', '[{"name":"Sườn non","qty":"600g","note":"chặt khúc"},{"name":"Cà chua","qty":"2 quả","note":"cắt múi"},{"name":"Giấm","qty":"2 muỗng canh","note":"tạo chua"},{"name":"Đường","qty":"2 muỗng canh","note":"tạo ngọt"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"nêm chính"}]', '["Luộc sườn sơ 5 phút.","Chiên sườn vàng đều.","Xào cà chua cho nhuyễn.","Thêm giấm, đường, nước mắm.","Cho sườn vào đảo.","Đun nhỏ lửa 10 phút.","Nêm lại."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bò xào hành tây', 'Bò xào hành tây ngon tuyệt', 15, 4, 'Easy', '[{"name":"Thịt bò","qty":"400g","note":"thái mỏng ngang thớ"},{"name":"Hành tây","qty":"1 củ","note":"cắt múi"},{"name":"Tỏi","qty":"3 tép","note":"băm"},{"name":"Dầu hào","qty":"1.5 muỗng canh","note":"ướp bò"}]', '["Ướp bò 10 phút.","Phi tỏi cho thơm.","Xào bò nhanh tay.","Cho hành tây vào.","Đảo 1–2 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Rau muống xào tỏi', 'Rau muống xào tỏi ngon tuyệt', 10, 4, 'Easy', '[{"name":"Rau muống","qty":"300g","note":"nhặt, rửa sạch"},{"name":"Tỏi","qty":"4 tép","note":"đập dập"},{"name":"Muối","qty":"1/2 muỗng cà phê","note":"nêm"}]', '["Làm nóng chảo với dầu.","Phi tỏi cho thơm.","Cho rau vào xào nhanh.","Nêm muối.","Đảo đều và tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Thịt ba chỉ rang cháy cạnh', 'Thịt ba chỉ rang cháy cạnh ngon tuyệt', 20, 4, 'Easy', '[{"name":"Thịt ba chỉ","qty":"500g","note":"cắt lát mỏng"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"nêm"},{"name":"Đường","qty":"1 muỗng canh","note":"tạo màu"}]', '["Cho thịt vào chảo rang khô.","Rang đến khi ra mỡ.","Thêm đường tạo màu.","Nêm nước mắm.","Đảo đến khi cháy cạnh."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Tôm rim mặn ngọt', 'Tôm rim mặn ngọt ngon tuyệt', 20, 4, 'Easy', '[{"name":"Tôm","qty":"400g","note":"lột vỏ, bỏ chỉ"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"nêm"},{"name":"Đường","qty":"1.5 muỗng canh","note":"tạo ngọt"},{"name":"Tỏi","qty":"3 tép","note":"băm"}]', '["Phi tỏi cho thơm.","Cho tôm vào đảo đều.","Thêm nước mắm và đường.","Rim nhỏ lửa.","Khi sệt thì tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Trứng chiên thịt băm', 'Trứng chiên thịt băm ngon tuyệt', 10, 4, 'Easy', '[{"name":"Trứng gà","qty":"3 quả","note":"đánh tan"},{"name":"Thịt băm","qty":"200g","note":"ướp nhẹ"}]', '["Trộn trứng với thịt.","Nêm gia vị.","Đổ vào chảo nóng.","Chiên vàng hai mặt."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh trứng cà chua', 'Canh trứng cà chua ngon tuyệt', 15, 4, 'Easy', '[{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Cà chua","qty":"2 quả","note":"cắt múi"}]', '["Xào cà chua cho mềm.","Thêm nước.","Cho trứng vào khuấy nhẹ.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh cải nấu thịt', 'Canh cải nấu thịt ngon tuyệt', 20, 4, 'Easy', '[{"name":"Rau cải","qty":"300g","note":"rửa sạch, cắt khúc"},{"name":"Thịt băm","qty":"200g","note":"ướp nhẹ muối tiêu"},{"name":"Hành tím","qty":"1 củ","note":"băm nhỏ"}]', '["Phi hành tím cho thơm.","Cho thịt băm vào xào tơi.","Thêm nước, đun sôi.","Cho rau cải vào.","Nêm gia vị, nấu thêm 3–5 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Đậu hũ sốt cà chua', 'Đậu hũ sốt cà chua ngon tuyệt', 15, 4, 'Easy', '[{"name":"Đậu hũ","qty":"3 miếng","note":"cắt vuông"},{"name":"Cà chua","qty":"3 quả","note":"băm nhuyễn"},{"name":"Hành tím","qty":"1 củ","note":"băm"}]', '["Chiên đậu hũ vàng các mặt.","Phi hành tím cho thơm.","Cho cà chua vào xào mềm.","Nêm gia vị vừa ăn.","Cho đậu vào sốt.","Đun nhỏ lửa 3–5 phút."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh khổ qua nhồi thịt', 'Canh khổ qua nhồi thịt ngon tuyệt', 40, 4, 'Easy', '[{"name":"Khổ qua","qty":"2 trái","note":"bỏ ruột"},{"name":"Thịt băm","qty":"300g","note":"trộn nấm mèo nếu có"},{"name":"Nấm mèo","qty":"20g","note":"ngâm nở, băm nhỏ"}]', '["Trộn thịt băm với nấm mèo.","Nhồi thịt vào khổ qua.","Đun nước sôi.","Cho khổ qua vào nấu.","Nấu lửa nhỏ 25–30 phút.","Nêm gia vị vừa ăn."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cơm chiên trứng', 'Cơm chiên trứng ngon tuyệt', 10, 4, 'Easy', '[{"name":"Cơm nguội","qty":"300g","note":"để tơi"},{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt nhỏ"}]', '["Làm nóng chảo với dầu.","Cho trứng vào đảo nhanh.","Thêm cơm nguội.","Đảo đều cho tơi hạt.","Nêm gia vị.","Rắc hành lá, tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cháo thịt băm', 'Cháo thịt băm ngon tuyệt', 30, 4, 'Easy', '[{"name":"Gạo","qty":"100g","note":"vo sạch"},{"name":"Thịt băm","qty":"150g","note":"ướp nhẹ"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt nhỏ"}]', '["Nấu gạo với nước thành cháo.","Cho thịt băm vào khuấy đều.","Nấu thêm 10 phút.","Nêm gia vị.","Rắc hành lá.","Dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Ức gà áp chảo', 'Ức gà áp chảo ngon tuyệt', 20, 4, 'Easy', '[{"name":"Ức gà","qty":"500g","note":"đập mỏng đều"},{"name":"Dầu olive","qty":"1 muỗng canh","note":"áp chảo"},{"name":"Muối","qty":"1/2 muỗng cà phê","note":"ướp"}]', '["Ướp ức gà với muối tiêu 10 phút.","Làm nóng chảo với dầu olive.","Áp chảo mặt thứ nhất 7–8 phút.","Lật mặt còn lại, áp chảo tiếp.","Gà chín thì tắt bếp.","Cắt lát khi dùng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Trứng luộc', 'Trứng luộc ngon tuyệt', 8, 4, 'Easy', '[{"name":"Trứng gà","qty":"2 quả","note":"rửa sạch"}]', '["Đun nước sôi.","Cho trứng vào nồi.","Luộc 7–8 phút.","Vớt ra ngâm nước lạnh.","Bóc vỏ khi dùng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cá hấp gừng', 'Cá hấp gừng ngon tuyệt', 25, 4, 'Easy', '[{"name":"Cá","qty":"600g","note":"làm sạch"},{"name":"Gừng","qty":"30g","note":"thái sợi"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt khúc"}]', '["Ướp cá với muối nhẹ.","Xếp gừng lên cá.","Cho cá vào xửng hấp.","Hấp 20–25 phút.","Rắc hành lá.","Dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Rau luộc thập cẩm', 'Rau luộc thập cẩm ngon tuyệt', 10, 4, 'Easy', '[{"name":"Bông cải","qty":"200g","note":"cắt miếng"},{"name":"Cà rốt","qty":"100g","note":"cắt lát"},{"name":"Đậu que","qty":"100g","note":"cắt khúc"}]', '["Đun nước sôi.","Cho rau cứng vào trước.","Luộc 5–7 phút.","Vớt ra để ráo.","Dùng kèm nước chấm."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cá chiên nước mắm', 'Cá chiên nước mắm ngon tuyệt', 20, 4, 'Easy', '[{"name":"Cá","qty":"600g","note":"làm sạch, để ráo"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"làm sốt"},{"name":"Tỏi","qty":"3 tép","note":"băm nhỏ"}]', '["Chiên cá vàng giòn hai mặt.","Phi tỏi cho thơm.","Cho nước mắm vào đun nhẹ.","Rưới sốt lên cá.","Tắt bếp và dùng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh chua cá', 'Canh chua cá ngon tuyệt', 35, 4, 'Easy', '[{"name":"Cá","qty":"500g","note":"cá lóc hoặc cá basa, cắt khúc"},{"name":"Cà chua","qty":"2 quả","note":"cắt múi cau"},{"name":"Me","qty":"30g","note":"dầm lấy nước chua"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt khúc"},{"name":"Rau thơm","qty":"50g","note":"ngò gai, rau om"}]', '["Đun sôi nước trong nồi.","Cho nước me vào tạo vị chua.","Thả cá vào nấu chín.","Cho cà chua vào nấu mềm.","Nêm nước mắm, muối cho vừa.","Cho hành lá và rau thơm.","Tắt bếp và dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh chua tôm', 'Canh chua tôm ngon tuyệt', 30, 4, 'Easy', '[{"name":"Tôm","qty":"400g","note":"lột vỏ, rút chỉ lưng"},{"name":"Cà chua","qty":"2 quả","note":"cắt múi"},{"name":"Me","qty":"30g","note":"lấy nước chua"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt khúc"}]', '["Đun sôi nước.","Cho nước me vào nồi.","Cho tôm vào nấu chín.","Thêm cà chua.","Nêm gia vị vừa ăn.","Cho hành lá vào.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Mì xào bò', 'Mì xào bò ngon tuyệt', 15, 4, 'Easy', '[{"name":"Mì trứng","qty":"2 vắt","note":"trụng sơ"},{"name":"Thịt bò","qty":"200g","note":"thái mỏng"},{"name":"Hành tây","qty":"1/2 củ","note":"cắt sợi"}]', '["Trụng mì qua nước sôi, để ráo.","Ướp bò nhẹ gia vị.","Phi tỏi cho thơm.","Xào bò nhanh tay.","Cho mì và hành tây vào.","Đảo đều, nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Mì xào trứng', 'Mì xào trứng ngon tuyệt', 10, 4, 'Easy', '[{"name":"Mì trứng","qty":"2 vắt","note":"trụng sơ"},{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt nhỏ"}]', '["Trụng mì, để ráo.","Phi hành cho thơm.","Cho trứng vào đảo nhanh.","Thêm mì vào chảo.","Nêm gia vị.","Đảo đều.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bún xào thịt', 'Bún xào thịt ngon tuyệt', 20, 4, 'Easy', '[{"name":"Bún tươi","qty":"400g","note":"xả nước cho tơi"},{"name":"Thịt heo","qty":"300g","note":"thái lát mỏng"},{"name":"Rau cải","qty":"100g","note":"cắt khúc"}]', '["Xào thịt heo cho chín.","Cho rau cải vào xào chung.","Thêm bún tươi.","Đảo đều tay.","Nêm gia vị vừa ăn.","Xào thêm 3–5 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Tôm hấp', 'Tôm hấp ngon tuyệt', 15, 4, 'Easy', '[{"name":"Tôm","qty":"500g","note":"rửa sạch, cắt râu"},{"name":"Sả","qty":"2 cây","note":"đập dập"}]', '["Đun sôi nước với sả.","Cho tôm vào xửng hấp.","Hấp 10–12 phút.","Tôm chín đỏ đều.","Lấy ra dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Mực xào cần tỏi', 'Mực xào cần tỏi ngon tuyệt', 20, 4, 'Easy', '[{"name":"Mực","qty":"400g","note":"làm sạch, cắt khoanh"},{"name":"Cần tây","qty":"200g","note":"cắt khúc"},{"name":"Tỏi","qty":"3 tép","note":"băm nhỏ"}]', '["Trụng mực nhanh qua nước sôi.","Phi tỏi cho thơm.","Cho mực vào xào nhanh.","Thêm cần tây.","Đảo đều 2–3 phút.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Mực chiên nước mắm', 'Mực chiên nước mắm ngon tuyệt', 20, 4, 'Easy', '[{"name":"Mực","qty":"400g","note":"cắt miếng vừa ăn"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"làm sốt"},{"name":"Tỏi","qty":"3 tép","note":"băm nhỏ"}]', '["Chiên mực vàng giòn.","Phi tỏi cho thơm.","Cho nước mắm vào đun nhẹ.","Cho mực vào đảo đều.","Đun 2 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bí đỏ xào tỏi', 'Bí đỏ xào tỏi ngon tuyệt', 12, 4, 'Easy', '[{"name":"Bí đỏ","qty":"300g","note":"gọt vỏ, thái mỏng"},{"name":"Tỏi","qty":"3 tép","note":"băm"}]', '["Phi tỏi cho thơm.","Cho bí đỏ vào xào.","Thêm ít nước.","Xào chín mềm.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Su su xào tỏi', 'Su su xào tỏi ngon tuyệt', 10, 4, 'Easy', '[{"name":"Su su","qty":"300g","note":"gọt vỏ, thái sợi"},{"name":"Tỏi","qty":"3 tép","note":"băm"}]', '["Phi tỏi cho thơm.","Cho su su vào xào.","Thêm ít nước.","Xào chín giòn.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Đậu que xào thịt', 'Đậu que xào thịt ngon tuyệt', 15, 4, 'Easy', '[{"name":"Đậu que","qty":"300g","note":"cắt khúc"},{"name":"Thịt heo","qty":"200g","note":"thái lát mỏng"},{"name":"Tỏi","qty":"3 tép","note":"băm nhỏ"}]', '["Phi tỏi cho thơm.","Cho thịt heo vào xào chín.","Cho đậu que vào đảo đều.","Thêm ít nước.","Xào đến khi đậu chín.","Nêm gia vị vừa ăn.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cà chua xào trứng', 'Cà chua xào trứng ngon tuyệt', 10, 4, 'Easy', '[{"name":"Cà chua","qty":"3 quả","note":"cắt múi cau"},{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Hành lá","qty":"2 nhánh","note":"cắt nhỏ"}]', '["Phi hành cho thơm.","Cho cà chua vào xào mềm.","Đổ trứng vào khuấy nhẹ.","Nêm gia vị vừa ăn.","Đảo nhanh tay.","Rắc hành lá.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Gà chiên nước mắm', 'Gà chiên nước mắm ngon tuyệt', 25, 4, 'Easy', '[{"name":"Thịt gà","qty":"600g","note":"chặt miếng vừa ăn"},{"name":"Nước mắm","qty":"3 muỗng canh","note":"làm sốt"},{"name":"Tỏi","qty":"4 tép","note":"băm"},{"name":"Đường","qty":"1.5 muỗng canh","note":"cân vị"}]', '["Chiên gà vàng giòn.","Phi tỏi cho thơm.","Cho nước mắm và đường vào nấu sốt.","Cho gà vào đảo đều.","Đun nhỏ lửa 3–5 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Gà rang sả ớt', 'Gà rang sả ớt ngon tuyệt', 30, 4, 'Easy', '[{"name":"Thịt gà","qty":"600g","note":"chặt miếng"},{"name":"Sả","qty":"3 cây","note":"băm nhỏ"},{"name":"Ớt","qty":"2 trái","note":"băm"},{"name":"Nước mắm","qty":"2 muỗng canh","note":"nêm"}]', '["Phi sả ớt cho thơm.","Cho gà vào đảo săn.","Thêm nước mắm.","Rang lửa vừa.","Rang đến khi gà chín và sệt.","Nêm lại.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh mồng tơi nấu thịt', 'Canh mồng tơi nấu thịt ngon tuyệt', 20, 4, 'Easy', '[{"name":"Mồng tơi","qty":"300g","note":"rửa sạch"},{"name":"Thịt băm","qty":"200g","note":"ướp nhẹ"},{"name":"Hành tím","qty":"1 củ","note":"băm"}]', '["Phi hành tím cho thơm.","Cho thịt băm vào xào.","Thêm nước đun sôi.","Cho mồng tơi vào.","Nêm gia vị.","Nấu thêm 3–5 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh rong biển thịt băm', 'Canh rong biển thịt băm ngon tuyệt', 20, 4, 'Easy', '[{"name":"Rong biển khô","qty":"20g","note":"ngâm nở"},{"name":"Thịt băm","qty":"200g","note":"ướp nhẹ"},{"name":"Dầu mè","qty":"1 muỗng cà phê","note":"tạo mùi"}]', '["Phi thịt băm với dầu mè.","Thêm nước đun sôi.","Cho rong biển vào.","Nấu 10 phút.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bò xào cần tỏi', 'Bò xào cần tỏi ngon tuyệt', 15, 4, 'Easy', '[{"name":"Thịt bò","qty":"400g","note":"thái mỏng"},{"name":"Cần tây","qty":"200g","note":"cắt khúc"},{"name":"Tỏi","qty":"3 tép","note":"băm"}]', '["Ướp bò nhẹ gia vị.","Phi tỏi cho thơm.","Xào bò nhanh tay.","Cho cần tây vào.","Đảo đều 2 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cá chiên giòn', 'Cá chiên giòn ngon tuyệt', 15, 4, 'Easy', '[{"name":"Cá","qty":"500g","note":"làm sạch, để ráo"},{"name":"Bột chiên giòn","qty":"50g","note":"áo cá"}]', '["Áo cá qua bột.","Làm nóng dầu.","Chiên cá vàng giòn.","Vớt ra để ráo.","Dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Tôm xào bơ tỏi', 'Tôm xào bơ tỏi ngon tuyệt', 20, 4, 'Easy', '[{"name":"Tôm","qty":"400g","note":"lột vỏ, rút chỉ"},{"name":"Bơ","qty":"30g","note":"bơ lạt"},{"name":"Tỏi","qty":"4 tép","note":"băm"}]', '["Phi tỏi với bơ.","Cho tôm vào xào.","Đảo đều đến khi tôm chín.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh bí đỏ nấu thịt', 'Canh bí đỏ nấu thịt ngon tuyệt', 25, 4, 'Easy', '[{"name":"Bí đỏ","qty":"400g","note":"gọt vỏ, cắt khúc"},{"name":"Thịt băm","qty":"200g","note":"ướp nhẹ"},{"name":"Hành tím","qty":"1 củ","note":"băm"}]', '["Phi hành tím cho thơm.","Cho thịt băm vào xào.","Thêm nước đun sôi.","Cho bí đỏ vào.","Nấu đến khi bí mềm.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bí đỏ hấp', 'Bí đỏ hấp ngon tuyệt', 15, 4, 'Easy', '[{"name":"Bí đỏ","qty":"400g","note":"gọt vỏ, cắt miếng"}]', '["Chuẩn bị xửng hấp.","Cho bí đỏ vào xửng.","Hấp 12–15 phút.","Kiểm tra bí mềm.","Lấy ra dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Su su luộc', 'Su su luộc ngon tuyệt', 10, 4, 'Easy', '[{"name":"Su su","qty":"400g","note":"gọt vỏ, cắt miếng"}]', '["Đun nước sôi.","Cho su su vào.","Luộc 7–10 phút.","Vớt ra để ráo.","Dùng kèm nước chấm."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Đậu hũ chiên sả ớt', 'Đậu hũ chiên sả ớt ngon tuyệt', 20, 4, 'Easy', '[{"name":"Đậu hũ","qty":"3 miếng","note":"cắt vuông"},{"name":"Sả","qty":"2 cây","note":"băm nhỏ"},{"name":"Ớt","qty":"2 trái","note":"băm"},{"name":"Nước mắm","qty":"1.5 muỗng canh","note":"nêm"}]', '["Chiên đậu hũ vàng giòn.","Phi sả ớt cho thơm.","Cho nước mắm vào.","Cho đậu vào đảo đều.","Rang nhỏ lửa 3–5 phút.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh trứng rong biển', 'Canh trứng rong biển ngon tuyệt', 15, 4, 'Easy', '[{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Rong biển khô","qty":"15g","note":"ngâm nở"}]', '["Đun sôi nước.","Cho rong biển vào.","Nấu 5 phút.","Cho trứng vào khuấy nhẹ.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cơm chiên Dương Châu', 'Cơm chiên Dương Châu ngon tuyệt', 15, 4, 'Easy', '[{"name":"Cơm nguội","qty":"300g","note":"để tơi"},{"name":"Trứng gà","qty":"1 quả","note":"đánh tan"},{"name":"Lạp xưởng","qty":"50g","note":"cắt hạt lựu"},{"name":"Đậu Hà Lan","qty":"50g","note":"luộc sơ"}]', '["Phi lạp xưởng cho ra mỡ.","Cho trứng vào đảo.","Thêm cơm nguội.","Cho đậu Hà Lan vào.","Đảo đều, nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Bún thịt xào', 'Bún thịt xào ngon tuyệt', 20, 4, 'Easy', '[{"name":"Bún tươi","qty":"400g","note":"xả nước cho tơi"},{"name":"Thịt heo","qty":"300g","note":"thái mỏng"},{"name":"Rau xà lách","qty":"100g","note":"rửa sạch"}]', '["Xào thịt heo cho chín.","Nêm gia vị vừa ăn.","Cho bún vào đảo nhẹ.","Tắt bếp.","Ăn kèm rau xà lách."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Cá hấp sả', 'Cá hấp sả ngon tuyệt', 25, 4, 'Easy', '[{"name":"Cá","qty":"600g","note":"làm sạch"},{"name":"Sả","qty":"3 cây","note":"đập dập"}]', '["Xếp sả dưới đáy xửng.","Đặt cá lên trên.","Hấp 20–25 phút.","Kiểm tra cá chín.","Lấy ra dùng nóng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Tôm hấp sả', 'Tôm hấp sả ngon tuyệt', 15, 4, 'Easy', '[{"name":"Tôm","qty":"500g","note":"rửa sạch"},{"name":"Sả","qty":"2 cây","note":"đập dập"}]', '["Đun nước với sả.","Cho tôm vào xửng.","Hấp 10–12 phút.","Tôm chín đỏ.","Lấy ra dùng."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Canh chua thịt', 'Canh chua thịt ngon tuyệt', 30, 4, 'Easy', '[{"name":"Thịt heo","qty":"400g","note":"cắt lát"},{"name":"Cà chua","qty":"2 quả","note":"cắt múi"},{"name":"Me","qty":"30g","note":"lấy nước chua"}]', '["Đun sôi nước.","Cho nước me vào.","Cho thịt vào nấu chín.","Thêm cà chua.","Nêm gia vị.","Tắt bếp."]', 1, NOW());
INSERT INTO recipes (name, description, cook_time, servings, difficulty, ingredients, steps, active, created_at) VALUES ('Trứng hấp', 'Trứng hấp ngon tuyệt', 15, 4, 'Easy', '[{"name":"Trứng gà","qty":"2 quả","note":"đánh tan"},{"name":"Nước","qty":"120ml","note":"nước ấm"}]', '["Đánh trứng với nước.","Lọc hỗn hợp cho mịn.","Đổ vào bát.","Hấp lửa nhỏ 12–15 phút.","Lấy ra dùng nóng."]', 1, NOW());

SET FOREIGN_KEY_CHECKS=1;
